### ISSUE TITLE
Machine_Learning/Design_Tutorials/07-yolov4-tutorial  quantize_yolov4.sh  error

### ISSUE THREAD

**Issue by hopesala** [Xilinx/Vitis-Tutorials#36]
my environment is 
vai_q_tensorflow --version
**Vai_q_tensorflow v1.2.0 build for Tensorflow 1.15.2**

I am training my own dataset, all is good , I got yolov4-obj_final.weights from yolov4 darknet train process
and convert it to **yolov4-obj-new.h5** and **tf_model_obj.pb** files   
in the quantize_yolov4.sh process, I place tf_calib.txt and val2017 folder at the right place and then

./quantize_yolov4.sh 
INFO: Checking Float Graph...
Traceback (most recent call last):
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/bin/vai_q_tensorflow", line 11, in <module>
    sys.exit(run_main())
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/contrib/decent_q/python/decent_q.py", line 943, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/contrib/decent_q/python/decent_q.py", line 942, in <lambda>
    my_main = lambda unused_args: main(unused_args, FLAGS)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/contrib/decent_q/python/decent_q.py", line 621, in main
    flags.skip_check)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/contrib/decent_q/python/decent_q.py", line 343, in quantize_frozen
    check_float_graph(input_graph_def, input_fn, q_config, s_config)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/contrib/decent_q/python/decent_q.py", line 257, in check_float_graph
    inputs = input_fn(iter=0)
  File "./yolov4_graph_input_keras_fn.py", line 90, in calib_input
    custom_image = cv2.resize(image, size, interpolation=cv2.INTER_NEAREST)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

is the problem caused by tf_calib.txt and val2017 folder, because the content  is not from my own data? is this the reason for error , and how to solve this problem, big thanks for advance!

**Comment by hopesala** [comment]
@rwarmstr can you help me solve the problem, thanks very much!~

**Comment by hopesala** [comment]
it is caused by the content path in the tf_calib.txt
solved~
